name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to registry
      run: |
        echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{github.sha}}platform-task
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/interview-task
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG


